import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Toaster } from '../components/ui/sonner';
import { ReactQueryProvider } from '@/lib/react-query';
import { AuthGuard } from '@/components/auth/auth-guard';
import { UserProvider } from '@/components/providers/user-provider';

const inter = Inter({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'ChatApp',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${inter.className} antialiased`}>
        <ReactQueryProvider>
          <UserProvider>
            <AuthGuard>
              <Toaster />
              {children}
            </AuthGuard>
          </UserProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
